name: eu_trading_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # UI & Charts
  cupertino_icons: ^1.0.2
  fl_chart: ^0.65.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.19.0
  
  # Phone & Voice
  country_code_picker: ^3.0.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/